[package]
name = "purl-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptonic = "0.3.0"
leptos = { version = "0.5.4", features = ["csr"] }
leptos_meta = { version = "0.5.4", features = ["csr"] }

[build-dependencies]
leptonic-theme = "0.3.0"
leptos-tiptap-build = "0.2.4"
